#spring.application.name=pedido
spring:
  application:
    name: pedido

  datasource:
    url: jdbc:mysql://localhost:3306/pedido-db
    username: admin
    password: admin

  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui.html

server:
  servlet:
    context-path: /
  port: '8080'
