spring:
  kafka:
    consumer:
      group-id: pedido-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:29092

springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui.html

server:
  servlet:
    context-path: /
  port: '8081'

kafka:
  topic: pedido-topic